# [stations.KALX]
# ignores = ["Arts In Review"]

# [stations.KPOO]
# ignores = [
#     "KPOO San Francisco .*",
#     "KPOO Community News",
#     "Keep The Praise Gospel Show",
#     ".*Emmit Powell Gospel Caravan.*"
# ]

# [stations.Psyched]


[stations.KXLU]
